# Generated by Django 5.0.2 on 2024-03-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IrrigationData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("pump_status", models.BooleanField(blank=True, default=False)),
                ("date", models.DateField(auto_now_add=True)),
                ("time", models.TimeField(auto_now_add=True)),
                ("ph_level", models.DecimalField(decimal_places=2, max_digits=5)),
                ("moisture_level", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "soil_temperature",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "nitrogen",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Nitrogen (N)"
                    ),
                ),
                (
                    "phosphorus",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Phosphorus (P)"
                    ),
                ),
                (
                    "potassium",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Potassium (K)"
                    ),
                ),
            ],
        ),
    ]
